### ISSUE TITLE
Design a new logo

### ISSUE THREAD

**Issue by druskus20** [druskus20/templar#9]
Suggestions are appreciated :P

**Comment by guilherme-svg** [comment]
Do you already have the base colors?

**Comment by druskus20** [comment]
I'm open to suggestions, my current idea is some sort of templar shield, possibly with a cross in the middle. The shield would be divided into two halves, one would be a normal, classic shield, the other one would be a blueprint. 
I picture the blueprint being, well, blue, and maybe the cross red?. 
But as I said, I'm completely open to suggestions.

**Comment by druskus20** [comment]
what are you using for the logo? do you have anything like a Figma file that I could contribute to? @guilherme-svg

**Comment by guilherme-svg** [comment]
> what are you using for the logo? do you have anything like a Figma file that I could contribute to? @guilherme-svg


I use Inkscape, but I can share the project via PenPot, what's your email? That I share with you.

Link to view the project:

https://design.penpot.app/#/view/80da45c0-a6e6-11ec-a0b4-765163de8d2d?page-id=80da45c1-a6e6-11ec-a0b4-765163de8d2d&section=interactions&index=0&share-id=d1dda080-a6ef-11ec-a0b4-765163de8d2d

**Comment by druskus20** [comment]
I'll probably end up using Figma myself at some point, however, for now, here's my email @guilherme-svg. I don't know how active I'll be at the moment, since I am prioritizing other parts of the project
templar.druskus@gmail.com

**Comment by guilherme-svg** [comment]
I've already sent the invite @druskus20 , hope I helped.

**Comment by druskus20** [comment]
![image](https://user-images.githubusercontent.com/43417195/164232270-be267467-3ee3-4ee5-8b97-aa4d7f1064c8.png)

**Comment by druskus20** [comment]
Did some tweaking on the borders and colors
![Frame 3](https://user-images.githubusercontent.com/43417195/164232310-a5483791-607d-4048-b081-5922a7bd0492.png)

**Comment by druskus20** [comment]
Changed the colors a bit more, I'm settling with this logo for now at least. Closing this.
